frontend/config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  root to: 'hotels#index'
end

frontend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

frontend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'application'
end

frontend/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

frontend/app/helpers/application_helper.rb
module ApplicationHelper
end

frontend/app/views/hotels/edit.html.erb
<%= react_component 'HotelForm', { url: t("api_url.#{Rails.env}"), path: 'update', id: params[:id] } %>

frontend/app/views/hotels/index.html.erb
<%= react_component 'Hotels', { url: t("api_url.#{Rails.env}") + "hotels", base_url: t("base_url.#{Rails.env}") } %>

frontend/app/views/hotels/new.html.erb
<%= react_component 'HotelForm', { url: t("api_url.#{Rails.env}"), path: 'create' } %>

frontend/app/views/hotels/show.html.erb
<%= react_component 'Hotel', { url: t("api_url.#{Rails.env}") + "hotels/#{params[:id]}" } %>

frontend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelFrontend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Challenge - TMA', root_url, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(controller: 'hotels', action: 'new') %>">
              <%= link_to 'New Hotel', new_hotel_path %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>